# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false
language: node_js
node_js:
  - '0.12'
  - '4.0'
  - '4.1'
  - '5.0'
script: npm test && npm run-script report-coverage
